List environments and processes
mockoon/cli pull request #9
Opened 2020-12-12 13:33 UTC by mauriceackel

**Parent issue** 

Closes #6
Closes #7

**Technical implementation details**

I added [inquirer](https://oclif.io/docs/prompting) as suggested by the oclif docs to prompt the user for an environment or running process for the start and stop command respectively.

2020-12-14 20:42 UTC, 255kb requested changes
Thank you for this contribution. 
I made some comments. In addition, we should update the readme and add some tests (we could mock stdin I think https://github.com/oclif/fancy-test#stdin-mocking). 
I can take part of the work, let me know.

2020-12-14 20:42 UTC, 255kb commented on src/commands/start.ts
> +        message: 'select an environment',
```suggestion
        message: 'Please select an environment',
```

2020-12-14 20:42 UTC, 255kb commented on src/commands/stop.ts
> +        message: 'select a process',
```suggestion
        message: 'Please select a process',
```

2020-12-14 20:42 UTC, 255kb commented on src/commands/start.ts
> +      const environments = await parseDataFile<Export>(userFlags.data).then(data => listEnvironments(data));
We should reuse the data in the `prepareData` function line 77, to avoid loading the data twice.
Also, this implementation is missing a test that occurs in data.ts line 90-92 to check if the data file is compatible. 

On solution would be to extract the data loading, data compatibility test and 'route' filtering in a separated method and overload `prepareData` definition so it accepts either a path or directly the loaded data.

2020-12-14 20:42 UTC, 255kb commented on src/commands/stop.ts
> +        return;
You must disconnect PM2 otherwise the CLI will hang.

```suggestion
        ProcessManager.disconnect();
        
        return;
```

2020-12-15 21:44 UTC, mauriceackel commented
@255kb Thanks for the feedback! Would be great if you could have a look at the tests, I will look at how we can reuse the data best :)

2020-12-15 22:26 UTC, mauriceackel commented on src/commands/start.ts
> +      const environments = await parseDataFile<Export>(userFlags.data).then(data => listEnvironments(data));
I moved the check for file compatibility to the file parser function now and overloaded the `prepareData` function so that it can also receive already parsed `Export` data. I now load the data when the start command is invoked and use it for listing all environments and later as input for `prepareData`.
The only thing that is done twice now is the filtering for the environments (i.e. excluding routes I guess?!). I think this could be added to the parseDataFile function too?

Unless this is all flawed and we use the parseDataFile function for other things too. I only saw it used to load the export file but it has a generic type so I'm unsure.

2020-12-16 19:53 UTC, 255kb commented on src/commands/start.ts
> +      const environments = await parseDataFile<Export>(userFlags.data).then(data => listEnvironments(data));
@mauriceackel Thank you for the changes, it's working like a charm! 
You are right, the routes filtering can be move to the parseDataFile function. I will do this and try to write some tests. 

Thank you for your contribution!
As soon as I'm done with the tests I will publish a new version.

2020-12-16 19:56 UTC, merged